name: Deploy React to EC2

on:
  push:
    branches:
      - main  # main에 푸시/머지되었을 때 트리거

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # 원하는 버전 사용

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Copy files to EC2 using rsync over SSH
      uses: burnett01/rsync-deployments@7.0.2
      with:
        switches: -avzr --delete
        path: dist/
        remote_path: /home/ubuntu/portfolio/dist/
        remote_host: ${{ secrets.EC2_HOST }}
        remote_user: ubuntu
        remote_key: ${{ secrets.EC2_SSH_KEY }}
